FRINXio/frinx-inventory-server

- src/schema/global-types.ts
- src/schema/index.ts
- src/schema/nexus-typegen.ts
As per https://nexusjs.org/docs/guides/abstract-types
> fix abstract type strategy for 'node' - add __typename

- src/external-api/network-types.ts
- src/external-api/uniconfig.ts
- src/schema/device.ts
- add typed response type to UniConfig install call
- add error to the GraphQL mutation call (so the UI can handle unsuccessful installation
> Fix uc installation response

- .env.example
- .github/workflows/pr-check.yml
- README.md
- src/config.ts
- src/sync-zones.ts
- src/test/helpers.ts
Set default tenant for sync zones via environment ariable
> Tenant defined by environment variable

- package.json
- src/schema/device.ts
- src/uniconfig-shell.ts
- yarn.lock
HOW TO TEST:
you should see some logs in running frinx-inventory-server terminal when running query (ssh connection is open and `show` command is sent to server):
```
query {
devices {
edges {
node {
id
name
}
}
}
}
```
> uniconfig shell init

- .env.example
- .github/workflows/pr-check.yml
- docker-compose.yml
- src/arango-client.ts
- src/config.ts
- src/context.ts
- src/external-api/topology-discovery.ts
- src/external-api/topology-network-types.ts
- src/helpers/topology-helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
HOW TO TEST:
EDIT:
there is now running toplogy server:
`curl -X GET 10.19.0.5:8080/api/topology/health` with list of endpoints 
list of endpoints: https://github.com/FRINXio/helm-charts/blob/main/charts/krakend/config/settings/topology_discovery_settings.json 
arangodb: `10.19.0.5:8529`
```
ARANGO_URL="http://10.19.0.5:8529"
TOPOLOGY_DISCOVERY_API_URL=http://10.19.0.5:8080/api/topology/data
ARANGO_USER="root"
ARANGO_PASSWORD="frinx"
ARANGO_DB="lldp" #
```
section below is not needed anymore
--- 
- change `docker-compose.yml` - commnent out arango-local section (we will not run arango, because it would conflict with arango running in topology-discovery)
- clone https://github.com/FRINXio/topology-discovery
- run `./startup.sh -ms`, `docker swarm init` - this should stasrt topology …
> FD-402 topology history endpoints

- .env.example
- .github/workflows/pr-check.yml
- src/config.ts
- src/uniconfig-shell.ts
also to make posiible for DevOps to configure host for shell connections
> add .env variable for shell host config

- arango/data/phy_link.json
- arango/init.js
- arango/init.ts
- src/arango-client.ts
- src/external-api/topology-network-types.ts
- src/helpers/topology-helpers.ts
- tsconfig.production.json
> connected collection renamed

- src/external-api/topology-network-types.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
Add `deviceType` and `softwareVersion` to `GraphNode` in graphql.
> add device details to GraphNode

- src/external-api/helpers.ts
- src/external-api/topology-discovery.ts
- src/external-api/topology-network-types.ts
- src/helpers/device-helpers.ts
- src/helpers/device-types.ts
- src/helpers/topology-helpers.ts
- src/schema/api.graphql
- src/schema/device.ts
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
Replace coordinates saved/read from the postgresql to the arango db (topology api).
> replace coordinates from postgres with arango

- src/external-api/conductor-network-types.ts
- src/schema/workflow.ts
HOW TO TEST:
you can test it along with this PR https://github.com/FRINXio/frinx-frontend/pull/1243
> output parameters fix

- src/__generated__/scheduler.graphql.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/workflow.ts
added support for sorting in executed workflows table
> refactored executed workflows query to support sorting

- src/helpers/device-helpers.ts
Made filtering by device name in **Device Inventory** case insensitive as part of FD-561
https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?selectedIssue=FD-561
> made filtering by device name case insensitive

- src/helpers/event-handler.helpers.ts
- src/schema/api.graphql
- src/schema/event-handler.ts
- src/schema/nexus-typegen.ts
- src/schema/workflow.ts
https://frinxhelpdesk.atlassian.net/browse/FD-566?atlOrigin=eyJpIjoiZGVlODdlMWU0MWZhNDU0Y2E2ZmU0OTM1MWJhZDA1NDEiLCJwIjoiaiJ9
Added sorting to event handler page
Test with frontend branch `add-filter-pagination-to-event-handlers`
> added sorting to event handlers

- package.json
- src/helpers/device-helpers.ts
- src/schema/api.graphql
- src/schema/device.ts
- src/schema/nexus-typegen.ts
https://frinxhelpdesk.atlassian.net/browse/FD-569?atlOrigin=eyJpIjoiZjIyMTZmZjY1ZDk1NDQ3YTg0N2Q2YmZiNmE5NzRiYTEiLCJwIjoiaiJ9
updated device sorting, test with. frinx-frontend `update-device-sorting`
> updated device sorting

- src/__generated__/topology-discovery.graphql.ts
- src/external-api/topology-discovery-graphql.ts
- src/helpers/topology.helpers.ts
- src/schema/topology.ts
IMPORTANT:
first check https://github.com/FRINXio/frinx-inventory-server/pull/339
HOW TO INSTALL TOPOLOGY-DISCOVERY
PREREQUISITIES:
python3
pytho3-pip
pip install python-dotenv
pip install pyArango
INSTALL:
-  [git@github.com](mailto:git@github.com):FRINXio/topology-discovery.git
- checkout to branch `graphql-get-backup-implement`
- ./teardown.sh -dv (optional - only if you have previously run topology discovery)
- ./startup.sh -ms -dt -bt
- export PYTHONPATH="${PYTHONPATH}:/path/to/topology/discovery"
- export ARANGO_USERNAME=root
- export ARANGO_ROOT_PASSWORD=frinx
- cd /topology/discovery/repo/helper_scripts/import_arangodb_collections/
- python3 import_collections.py
> FD-540 backups query

- src/external-api/conductor-network-types.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/workflow.ts
changes made:
- added new properties to workflow input to be able to update workflow definition
- fix type definition of new properties for correct decoding of workflow definition and executed workflow
> add missing workflow definition properties to make updating more customizable

- src/helpers/resource-manager.helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/pool.ts
added pool properties to resource pools query
> add pool properties to resource pool

- prisma/seed.js
- prisma/seed.ts
- src/helpers/converters.ts
HOW TO TEST:
install new device (ping me and i will provide you with mount parameters)
> install device fix

- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
HOW TO TEST:
needs to be tested with topology-discovery v.1.3.x branch. test both (default and demo collections)
> lldp layer demo fix

- src/schema/device.ts
import csv and save as json object in prisma
> FD-627 csv import fix

- src/external-api/network-types.ts
- src/external-api/uniconfig.ts
- src/schema/transaction.ts
HOW TO TEST:
https://frinxhelpdesk.atlassian.net/browse/FD-667
> FD-667 revert changes fix

- package.json
- prisma/migrations/20240502084610_stream_table/migration.sql
- prisma/schema.prisma
- prisma/seed.js
- prisma/seed.ts
- src/helpers/device-helpers.ts
- src/helpers/id-helper.ts
- src/schema/api.graphql
- src/schema/global-types.ts
- src/schema/index.ts
- src/schema/nexus-typegen.ts
- src/schema/source-types.ts
- src/schema/stream.ts
- tsconfig.json
HOW TO TEST:
```
npx prisma migrate dev
npm prisma:seed
npm run dev
```
you should be able to query stream and add stream (`deviceName` should be existing device, `streamName` should be unique for device)
> FR-231 stream query added

- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/stream.ts
HOW TO TEST:
you should see new mutatuion `addStream` in playground
> add stream mutation changes

- prisma/migrations/20240619074216_add_blueprint_to_stream/migration.sql
- prisma/schema.prisma
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/stream.ts
remove and update stream mutations added
> FR-233 remove device stream implementation

- src/helpers/device-helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/stream.ts
HOW TO TEST: 
you can test `streams` query with `orderByInput` if its working correctly
> FR-237 stream columns sorting added

- prisma/migrations/20240718105212_location_country_optional/migration.sql
- prisma/schema.prisma
- src/__generated__/topology-discovery.graphql.ts
- src/external-api/kafka.ts
- src/external-api/topology-discovery-graphql.ts
- src/helpers/device-helpers.ts
- src/helpers/id-helper.ts
- src/helpers/location-helpers.ts
- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/device.ts
- src/schema/location.ts
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
- devcieMetadata endpoint added
- kafka messages sent when create/edit device
> FR-201 add edit device location

- prisma/migrations/20240722092527_add_stream_start_stop_time/migration.sql
- prisma/schema.prisma
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/stream.ts
this fixes stream list in story branch.
run 
`npx prisma migrate dev`
`npm run prisma:seed`
> Merge main to geomap story branch

- src/__generated__/topology-discovery.graphql.ts
- src/external-api/topology-discovery-graphql.ts
- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
merge story-mpls -> story-geomap
> Merge mpls

- src/__generated__/topology-discovery.graphql.ts
- src/external-api/topology-discovery-graphql.ts
- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/location.ts
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
- schema for mpls data was changed in topology discovery graphql api
- addLocation, updateLocation fix
> mpls changes

- src/external-api/topology-discovery-graphql.ts
- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?selectedIssue=FR-329
adjusted filtering of metadata and added phyDeviceName to netTopology query
> FR-329 - topology overlay integration

- src/__generated__/topology-discovery.graphql.ts
- src/external-api/topology-discovery-graphql.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?selectedIssue=FR-327
Added neighbor query for map topology devices, test on :5555
`query Neighbours($filter:  FilterNeighborInput) {
deviceInventory {
deviceNeighbor(filter: $filter){
neighbors{deviceName
deviceId}
}
}
}`
`{
"filter": {
"deviceName": "BH_SAOS502",
"topologyType": "PhysicalTopology"
}
}`
> Fr 327 show overlay topology

- src/__generated__/topology-discovery.graphql.ts
- src/external-api/topology-discovery-graphql.ts
- src/helpers/topology.helpers.ts
- src/schema/api.graphql
- src/schema/nexus-typegen.ts
- src/schema/topology.ts
HOW TO TEST:
you can check this query
```
query LspPath($deviceId: String!, $lspId: String!)  {
lspPath(deviceId: $deviceId, lspId: $lspId) {
path
metadata {
fromDevice
toDevice
signalization
uptime
}
} 
}
```
with variables
```
{
"deviceId": "R3JhcGhOb2RlOk1wbHNEZXZpY2UvMg",
"lspId": "6.6.6.6/32"
}
```
> FR-312 lsp path

- src/schema/device.ts
HOW TO TEST:
reading the code is enough
> remove device from cache before reading status

- src/external-api/topology-discovery-graphql.ts
- src/schema/topology.ts
Test: go to topology -> map layer and try search by name. Should work as contains, not only exact match.
> FD-715 add wildcards to search text
